### ISSUE TITLE
please check why not a html markup is rendered, but a string `ShallowWrapper {}`; 

### ISSUE THREAD

**Issue by pavelmickevic** [tusharshyoran/AdformAssignment#1]
https://github.com/tusharshyoran/AdformAssignment/blob/8212d27fe3ba19b18e8706f0b3e7bee0fdad22d1/src/components/CampaignList/__snapshots__/CampTable.test.js.snap#L3

please check why not a html markup is rendered

I was expecting to see somthing like this: 
https://github.com/tusharshyoran/AdformAssignment/blob/8212d27fe3ba19b18e8706f0b3e7bee0fdad22d1/src/components/DateRangeSelector/__snapshots__/DateRangeSelector.test.js.snap#L4-L25

**Comment by tusharshyoran** [comment]
Fixed the above now getting the whole html markup for the same.
