### ISSUE TITLE
please read the articles, why `==` is not that good as strict equal `===` operator

### ISSUE THREAD

**Issue by pavelmickevic** [tusharshyoran/AdformAssignment#4]
usually you don't wanna compare things with `==`

https://github.com/tusharshyoran/AdformAssignment/blob/8212d27fe3ba19b18e8706f0b3e7bee0fdad22d1/src/components/DateRangeSelector/DateRangeSelector.jsx#L22

please reply on this issue, why you think `==` is bad, and why `===` is better. 

https://github.com/getify/You-Dont-Know-JS/blob/2nd-ed/get-started/ch2.md#comparisons

**Comment by tusharshyoran** [comment]
By mistake i have used '==' in place of '==='. Usually it's a good practice and we tend to use strict equality (===) in place of '==' as it disallows any type conversions and only allow to check if both the value and type of the values are equal.

**Comment by pavelmickevic** [comment]
this is crucial mistake

never ever use this kind of comparison ==
this is the first place to check for possible bugs
