### ISSUE TITLE
FR: remove campaign in the table

### ISSUE THREAD

**Issue by pavelmickevic** [tusharshyoran/AdformAssignment#5]
please make a reducing function to remove a specific campaign from the list by campaigns Id. 

optionally, you can render the trashbin icon in the list, when clicked action is dispatched, and handled by this new reducing fn. 

https://github.com/tusharshyoran/AdformAssignment/blob/8212d27fe3ba19b18e8706f0b3e7bee0fdad22d1/src/redux/reducer/index.js#L12-L16

**Comment by pavelmickevic** [comment]
P.S. consider reusing constants in this file: 
https://github.com/tusharshyoran/AdformAssignment/blob/8212d27fe3ba19b18e8706f0b3e7bee0fdad22d1/src/redux/actions/index.js#L3

instead of hardcoding...

you already have the consts defined in `src\redux\actions\actionType.js`

**Comment by tusharshyoran** [comment]
> P.S. consider reusing constants in this file:
> https://github.com/tusharshyoran/AdformAssignment/blob/8212d27fe3ba19b18e8706f0b3e7bee0fdad22d1/src/redux/actions/index.js#L3
> 
> instead of hardcoding...
> 
> you already have the consts defined in `src\redux\actions\actionType.js`

Removed hardcoding and reused the constants declared in actionType.js

**Comment by tusharshyoran** [comment]
> please make a reducing function to remove a specific campaign from the list by campaigns Id.
> 
> optionally, you can render the trashbin icon in the list, when clicked action is dispatched, and handled by this new reducing fn.
> 
> https://github.com/tusharshyoran/AdformAssignment/blob/8212d27fe3ba19b18e8706f0b3e7bee0fdad22d1/src/redux/reducer/index.js#L12-L16

Implemented the trash icons with remove campaigns functionality
